on:
 push: 
  branches:
    - main
name: Deploy Website on push

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install and build project
        run: |
          npm install
          npm run build

      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          username: ${{ secrets.GIT_CPANEL_REACT_USERNAME }}
          password: ${{ secrets.GIT_CPANEL_REACT_PASSWORD }}
          server: ${{ secrets.GIT_CPANEL_REACT_SERVER }}
          protocol: ${{ secrets.GIT_CPANEL_REACT_PROTOCOL }}
          port: ${{ secrets.GIT_CPANEL_REACT_PORT }}
          local-dir: './dist/' 
          remote-dir: ${{ secrets.GIT_CPANEL_REACT_APP_URL }}
